# Don't touch this!
config-version: 1

# Here you can choose the worlds in which the gnomes can spawn.
# If type is set BLACKLIST, worlds listed here will be disabled.
# If type is set WHITELIST, only worlds listed here will be enabled.
# NOTE: Gnomes that already exist in a world will not be removed.
worlds-filter:
  type: BLACKLIST
  worlds:
    - world_name_1
    - world_name_2
    - world_name_3

# Here you can choose the biomes in which the gnomes can spawn.
# If type is set BLACKLIST, biomes listed here will be disabled.
# If type is set WHITELIST, only biomes listed here will be enabled.
# NOTE: Gnomes that already exist in a biome will not be removed.
#
# Biomes: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/block/Biome.html
biomes-filter:
  type: WHITELIST
  worlds:
    - PLAINS
    - FOREST
    - CHERRY_GROVE
    - SNOWY_PLAINS
    - DESERT
    - SAVANNA
    - FLOWER_FOREST
    - SUNFLOWER_PLAINS
    - STONY_SHORE
    - BEACH

# Here you will find the options regarding the spawn of gnomes.
spawn:
  # The chance of a gnome spawning (from 0.0 to 1.0).
  chance: 0.055
  # If true, it will attempt to spawn gnomes only during the day and not at night.
  only-at-day: true
  # The distance that must be between an existing gnome and the potential location of a new gnome before attempting to spawn.
  distance-between: 64.0

# The scale range (size) the gnome can have when spawning (where 1.0 is the normal size).
scale:
  min: 0.75
  max: 1.1

# The lifespan range (in seconds) the gnome will live.
life:
  min: 30
  max: 180

# Here you can choose the items that the gnome will throw on the ground while he is still alive.
random-item-drop:
  # Whether this function is enabled.
  enabled: true
  # The waiting time (in seconds) between attempts to throw an item.
  delay: 3.0
  # The chance to throw an item (from 0.0 to 1.0).
  chance: 0.0675
  # Here you can choose the items that the gnome can throw.
  #
  # To choose a material, simply type its name.
  # * For example: IRON_INGOT
  #
  # You can also use tags, putting a $ before the tag name.
  # * For example: $BEACON_PAYMENT_ITEMS
  #
  # You can also specify the amount of items, putting the number in parentheses.
  #
  # Materials: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html
  # Tags: https://minecraft.fandom.com/wiki/Tag#List_of_tags
  items:
    - BONE(1)
    - COD(2)
    - IRON_INGOT(2-6)
    - $BEACON_PAYMENT_ITEMS
    - GOLD_INGOT
    - GOLDEN_APPLE

# Here you can modify the plugin messages.
messages:
  reloading: "&6The plugin is being reloaded in another thread, wait a few seconds..."
  reload: "&6The plugin has been reloaded!"
  no-permission: "&cYou don't have the required permission to execute this command!"
  invalid-command: "&cThat command doesn't exist or was used incorrectly!"